spring.application.name=folio-field-resume-backend
server.port=8080
spring.jackson.default-property-inclusion=non_null
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/resume_data}
spring.data.mongodb.database=resume_data
